### PR TITLE
Linux- level up

### PR DESCRIPTION
**Pull request by Morbius00**
Hacktober Badge

## Linux level-up

Added a linux level up file with the basics to intermediate code

### CODE REVIEW

**Review by NamanManjkhola — APPROVED** [review]

**Comment by NamanManjkhola** [comment]
Merging the PR.
Thank You for contributing  🎉

**Comment by Morbius00** [comment]
hey hope you like the file if their is any issues please go through it .
and please dont forget to add the hacktober label in the pr
thanks ,
regards

**Review by NamanManjkhola — APPROVED** [review]

**Comment by 1Spirit1** [comment]
File reviewed by @NamanManjkhola 
mergining the PR.
Thank you @Morbius00  for contributing 🎉

**Comment by Morbius00** [comment]
thanks for merged

**Comment by Morbius00** [comment]
hey do you have any idea why the 7 days count down is not showing in my hacktober fest profile after merged

**Pull request merged**
