### PR TITLE
Linux Mint

### PR DESCRIPTION
**Pull request by kodepirate**

### CODE REVIEW

**Comment by kodepirate** [comment]
@1Spirit1 My work is done

**Comment by kodepirate** [comment]
By mistake I removed the assign tag, will you please add it  and the repo is ready to merge so merge it @1Spirit1

**Review by 1Spirit1 — APPROVED** [review]

**Comment by 1Spirit1** [comment]
Merging your PR.🎉
Thanks for contributing

**Comment by kodepirate** [comment]
Thank you @1Spirit1 ☺️

**Pull request merged**
